config/routes.rb
PhotoContest::Application.routes.draw do

  root :to=>'welcome#show'
  resources :favorites, :only=>[:create, :index]
  resources :games do
    collection do
      post 'play'
      get 'hit_api'
      get 'start_with_user_tags'
      get 'start'
      get 'show'
    end 

    member do 
      get 'play' #for starting a game when the game has already been created, by way of having user chosen tags 
      get 'start'
      post 'submit_user_tag'
    end 
  end 
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  serialize :image
  validates_uniqueness_of :image
end

app/models/game.rb
class Game < ActiveRecord::Base
  
  serialize :pairs, Array
  serialize :images, Array
  serialize :votes, Array

  
  after_initialize do
    self.pairs ||= []
    self.images ||= []
    self.votes ||= []
    self.choice ||= 0
  end 

  def winners
    images.map{|i| i if i[:winner]==1 }.compact
  end 
  
  #precious
  def over?
    self[:round] == 0
  end 
  
  def choice_number
    self[:choice]
  end 

  def choice_number=(n)
    self[:choice]=n
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites=Favorite.all
  end 
  
  def create 
    Favorite.create(params[:favorite])
  end 

end

app/controllers/games_controller.rb
require 'rubygems'

class GamesController < ApplicationController

  include PhotoApi
  include RandomTags
  
  def start_with_user_tags
    reset_game
    @possible_tags = possible_tags.uniq
    render 'start_with_user_tags'
  end 
  
  def submit_user_tag
    #to be used only as xhr
    session[:user_tags] ||= []
    session[:user_tags] << params[:commit]
    tags=session[:user_tags].uniq.map{|t| "<span>" + t + "&nbsp;</span>"  }.join("") 
    
    respond_to do |format|
        format.js { render :text=>"reload_tag_area('" + tags + "');"  } 
    end 
    return
  end 

  def start #game
    reset_game
    new_round
    play
  end 

  def play
    #play is called upon each vote for a photo. 
    
    @game ||= Game.find(session[:game][:game_id])
    if params[:vote]
      @game.images[params[:vote].to_i][:winner] = 1 
      @game.pairs.pop
      @game.save
    end 

    if @game.pairs.empty?
      if @game.winners.size == 1 
        #end of game. 
        @game_over=@game.winners.first
        post_winners
        post_done
      else
        new_round
      end 
    end 

    @game.choice_number +=1
    @game.save
    @tup=@game.pairs.last  
    @leaderboard=@game.images.map{|i| i if i[:winner]==1 }.compact
    render 'show'
  end 

    def hit_api
      #sends a request to the photos api and dumps the result out the page. mainly for debugging and testing. 
      @req = request.fullpath
      @res = 
      if params[:round]
        self.send( params[:req].to_sym , params[:round] ) 
      else
        self.send params[:req] 
      end 
      #~ @res =  self.send params[:req]
      render 'debug'
    end 
  
  def post_winners
    #at the end of the round, notify the api of the winners of the round .
    winners = []
    @game[:images].each do |im|
      winners<<im['image'] if im[:winner]==1
    end 
    post_store_round_results(@game.round,winners.to_json)
  end 
  
  def new_round
    #tell server results of round that is ending
    if @game.round > 0 
      post_winners
    end
    #set up new round

    if @game.over? 
      @game[:images] = get_images_request 
    else  
      @game[:images] = @game.winners 
    end 
    @game.save
    session[:game][:total_rounds] =4 
    @game[:images].each do |img|
      img[:winner]=0
    end 
    isi=@game[:images].size
    pairs=[]
    (0..isi-1).each do |i| 
      pairs << [i, i+1] if i.even?
    end 
    @game.pairs=pairs.shuffle
    @game.round +=1
    @game.choice_number=0  
    @game.save
    session[:chooses] = @game.pairs.size
    @game
  end 

  
  def reset_game
    @game = params[:id] ? Game.find(params[:id]) : Game.new    
    @game.tags=determine_tags.join(' ')
    @game[:images] =  @yielded_images
    @game.save
    session[:game]={:game_id=>@game.id }
  end 

 
  

  private
  def determine_tags
  # we can't just pick 4 random words and go.
  # it's possible the api won't return enough photos for a given set of words
  # so we start with a long word list (see below). We hit the api with thtat list
  # if we don't get enough photos, we trim the list and try again. As long as you start 
  # with a reasonably sized tag list, it returns soon enough. 
    tags=[]
    tags_to_return=[]
    #this is the implementation of 
logger.info("session tags  " + session[:user_tags].inspect)
logger.info("session tags  " + session[:user_tags].inspect)
logger.info("session tags  " + session[:user_tags].inspect)
logger.info("session tags  " + session[:user_tags].inspect)
logger.info("session tags  " + session[:user_tags].inspect)
    if session[:user_tags] 
      tags=session.delete(:user_tags) 
    else
      # this number is important. if too high, it will create too long a tag list, and
      # make thus fail to find any photos, and thus have to try again. 3 seems about right. 
      # also, the theme generator returns two words, a noun and an adjective, so 3 actually starts you out with 6 
      # words. 
      3.times do 
        tags += RandomTags.pair #rmtg.randthemename.split('_') 
      end   
    end 
    yielded_images=[]
    while yielded_images.size < 16 && tags.length>0
      tags=tags.shuffle 
      tags_to_return=tags.clone  # get them before the pop, in case we're all done.
      post_reset(tags)
      yielded_images=get_images_request 
      tags.pop 
    end   
    @yielded_images=yielded_images
    tags_to_return
  end 
  
  def possible_tags
    pt=[]
    100.times do 
       @possible_tags = pt += RandomTags.pair
    end 
     @possible_tags
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favorites/index.html.erb
<table id="pic-showdown">
  <%@favorites.each do |f| %> 
    <tr>
      <td>
      <a href='<%=f.image rescue '' %>'><img src='<%=f.image rescue '' %>' /></a>
      <%= f.title %>
      </td>
    </tr>
    <% end %> 
  </table>

app/views/games/debug.html.erb
<div>
Debug
<dl>
  <dt>Your Request</dt>
    <dd><%=@req %></dd>
  <dt>The Response</dt>
    <dd><%=@res.inspect %></dd>
</dl> 
</div>

app/views/games/show.html.erb
<% if !@game %>
<p>Doesnt seem to be a game going on</p>
<% elsif !@game_over %> 
  <div id='game-status'>Game in progress... round <%=@game[:round].to_s %> / <%=session[:game][:total_rounds].to_s%> choice <%=@game[:choice].to_s %> / <%=session[:chooses].to_s%></div>
  <%=raw "Tags used this contest: <b>#{@game.tags}</b>" if @game.tags %> 
  
  <div id="current-winners">
    <% if @leaderboard.size > 0 %>
      Winners thus far:<br/>
      <table class="current-winners">
          <%@leaderboard.each do |image| %>
          <tr>
            <td><%=image_tag(image['image']['url'])%> </td>
          </tr>
          <% end %>
      </table>
    <% end %> 
  </div>
  
  <p>Click the photo you like best:</p>
  <table id="pic-showdown">
    <tr>
      <td>
      <%= form_for Favorite.new, :remote=>true  do |f| %> 
          <%= f.text_field :image,:type=>:hidden, :value=>(@game[:images][@tup.first]['image']['url'] rescue 'no-url-provided') %> 
          <%= f.text_field :title,:type=>:hidden, :value=>(@game[:images][@tup.first]['image']['title'] rescue 'no title provided')%> 
          <%= f.submit "Add to Favorites" %> 
      <%end %>
      <%= link_to image_tag(@game[:images][ @tup.first ]['image']['url']) , play_games_path(:vote=>@tup.first), :method=>:post %>
      <%= (@game[:images][ @tup.first ]['image']['title'])%>
      </td>
      <td>
      <%= form_for Favorite.new, :remote=>true do |f| %> 
          <%= f.text_field :image,:type=>:hidden, :value=>@game[:images][@tup.last]['image']['url'] %> 
          <%= f.text_field :title,:type=>:hidden, :value=>@game[:images][@tup.last]['image']['title'] %> 
          <%= f.submit "Add to Favorites" %> 
      <%end %>
      <%= link_to image_tag(@game[:images][ @tup.last ]['image']['url']) , play_games_path(:vote=>@tup.last), :method=>:post  %>
      <%= (@game[:images][ @tup.last ]['image']['title'])%>
      </td>
    </tr>
  </table>

<% elsif @game_over %>
    <p>A winner has emerged:</p>
    <div style="text-align:center;margin:auto;">
    <%= image_tag @game_over['image']['url'] %> 
    <%= @game_over['image']['title'] %> 
    </div>
    <h4 style="margin:auto;"><%= link_to "Click here to play again",start_games_path %> </h4>

<% else  %>
    <%= link_to "Click here to start", start_games_path %> 
<% end %> 

<br/>

app/views/games/start_with_user_tags.html.erb
<div>Here are some tags to choose from. They'll be used to pick the photos.</div> 

<% @possible_tags.each do |pt| %>
  <div style="display:inline;text-align:justify;">
  <%= form_for @game , :url=>submit_user_tag_game_path(@game),:html=>{:style=>"display:inline;", :method=>:post} , :remote=>true do |f|  %> 
    <% f.text_area :tags, :value=>pt.to_s, :type=>:hidden %>
    <% f.submit pt %> 
  <% end %> 
  </div>
<% end %>

<h6>Chosen tags:</h6>
<div id="chosen-tags">

</div>

<h2><%=link_to "Start Game", start_game_path(@game) %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoContest</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag  :defaults  %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="welcome-content">

  <h3 style="text-align:center;">Photo Choosing Contest</h3>
  <h5 style="text-align:center;">as implemented by David Heitzman</h5>
    
  <div class="navbar">
  <h6>
    <% if @game && !@game_over %> 
      <%= link_to "Home",root_url, :confirm=>"Are you sure? You'll lose the current game in progress." %> | 
      <%= link_to "Game Reset",start_games_path, :confirm=>"Are you sure? You'll lose the current game in progress." %> | 
      <%=link_to "Start Game With Your Own Tags", start_with_user_tags_games_path, :confirm=>"Are you sure? You'll lose the current game in progress." %> | 
      <%= link_to "View Favorites (#{Favorite.all.size})", favorites_path %> 
    <% else %> 
      <%= link_to "Home",root_url %> | 
      <%= link_to "Game Reset",start_games_path %> | 
      <%=link_to "Start Game With Your Own Tags",start_with_user_tags_games_path %> | 
      <%= link_to "View Favorites (#{Favorite.all.size})", favorites_path %> 
    <% end %> 
  </h6>
  </div>
  <%= yield %>
</div>
<div id='footer-content'>
  <div> 
  <p>Some debugging information for you:  Rails.env => <%= Rails.env %>  </p>
  <p>Some handy controls for the api:

   <%= link_to 'get_default_request'.humanize ,hit_api_games_path(:req=>'get_default_request')%>  
   <%= link_to 'get_images_request'.humanize ,hit_api_games_path(:req=>'get_images_request')%>  
   <%= link_to 'get_rounds_request'.humanize ,hit_api_games_path(:req=>'get_rounds_request')%>  
   <%= link_to 'get_round_request'.humanize ,hit_api_games_path(:req=>'get_round_request', :round=>(@game.round rescue 0) )%>  
   <%= link_to 'post_reset'.humanize ,hit_api_games_path(:req=>'post_reset')%>  
   <%= link_to 'post_done'.humanize ,hit_api_games_path(:req=>'post_done')%>  
   <%= link_to 'post_store_round_results'.humanize ,hit_api_games_path(:req=>'post_store_round_results')%>  
  </p>
  </div>
  <p>Issues: Occasional  500 after choosing a photo. I believe this is because of some photos not having a title or url, which I'll be debugging momentarily.  </p> 

  <p>Issues: Occasional  passenger error page. Refresh may fix. Dreamhost's rails support is generally spotty.  </p> 
</div>
</body>
</html>

app/views/welcome/debug.html.erb
<div>
Debug
<dl>
  <dt>Your Request</dt>
    <dd><%=@req %></dd>
  <dt>The Response</dt>
    <dd><%=@res.inspect %></dd>
</dl> 
</div>

app/views/welcome/show.html.erb
<h2>Welcome!</h2>

<p>This little app lets you participate in a photo contest.</p>
<p>You will choose 1 lucky winner from 16 photos.</p.<p> During the game, you are shown 1 pair of photos at a time. You click on the photo that you like best, and then another pair comes up. This keeps going until you complete a full round. At the end of the game you get to see which photo won. You can play as many times as you'd like.</p>
<p>The photos are obtained from flickr, with random tag words. You can also choose your own tags, by clicking "Start Game With Your Own Tags" above.</p><p>If you see a photo you like during the game, click "Add to Favorites". You can look at your favorites by clicking the "Favorite Pictures" link above. Then click the back button on your browser to continue choosing photos. </p>
<h2 style="text-align:center;"><%= link_to "Start Game",start_games_path %> </h2>

app/views/welcome/start_with_user_tags.html.erb
<div> Let's choose some tags! </div>
<a href="#" class="user_selected_tag">my tag</a>